# Generated by Django 5.2.13 on 2026-04-16 17:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма долга')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Закрыт')], default='unpaid', max_length=20, verbose_name='Статус')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты')),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.credit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Оплата кредита',
                'verbose_name_plural': 'Оплаты кредитов',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата продажи')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('credit', 'Кредит')], default='cash', max_length=20, verbose_name='Тип оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая себестоимость')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая прибыль')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer', verbose_name='Клиент')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.seller', verbose_name='Продавец')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='sales.sale', verbose_name='Продажа'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество (кг)')),
                ('sale_price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи за кг')),
                ('cost_price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Себестоимость за кг')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма строки')),
                ('line_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Себестоимость строки')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Прибыль')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='core.product', verbose_name='Товар')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Строка продажи',
                'verbose_name_plural': 'Строки продаж',
                'ordering': ['id'],
            },
        ),
    ]
