# Generated by Django 5.2.13 on 2026-04-16 18:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpayment',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма продажи'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Прибыль'),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс кассы')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Касса магазина',
                'verbose_name_plural': 'Кассы магазинов',
                'ordering': ['store__name'],
            },
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='CreditPayment',
        ),
    ]
