# Generated by Django 5.2.13 on 2026-04-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0002_remove_creditpayment_credit_remove_sale_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('credit', 'Кредит')], default='cash', max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
