# Generated by Django 5.2.13 on 2026-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0003_sale_customer_sale_payment_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['balance'], name='sales_cashr_balance_71398f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'date'], name='sales_sale_store_i_fa4844_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_type', 'date'], name='sales_sale_payment_a61683_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
    ]
