# Generated by Django 5.2.13 on 2026-05-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_inventory_p_date_62d889_idx_and_more'),
        ('sales', '0004_cashregister_sales_cashr_balance_71398f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма продажи')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_batches', to='inventory.purchaseitem', verbose_name='Партия закупки')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='sales.saleitem', verbose_name='Строка продажи')),
            ],
            options={
                'verbose_name': 'Распределение продажи по партии',
                'verbose_name_plural': 'Распределения продаж по партиям',
                'db_table': 'sale_item_batches',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['sale_item'], name='sale_item_b_sale_it_118a3f_idx'), models.Index(fields=['purchase_item'], name='sale_item_b_purchas_cd5efc_idx')],
            },
        ),
    ]
