# Generated by Codex on 2026-05-08

from collections import defaultdict
from decimal import Decimal

from django.db import migrations


ZERO_QTY = Decimal("0.000")
ZERO_MONEY = Decimal("0.00")


def money(value):
    return (value or ZERO_MONEY).quantize(Decimal("0.01"))


def backfill_sale_item_batches(apps, schema_editor):
    PurchaseItem = apps.get_model("inventory", "PurchaseItem")
    Sale = apps.get_model("sales", "Sale")
    SaleItem = apps.get_model("sales", "SaleItem")
    SaleItemBatch = apps.get_model("sales", "SaleItemBatch")

    allocated_by_purchase = defaultdict(lambda: ZERO_QTY)
    for batch in SaleItemBatch.objects.all():
        allocated_by_purchase[batch.purchase_item_id] += batch.quantity

    sale_items = (
        SaleItem.objects.select_related("sale")
        .filter(batches__isnull=True)
        .order_by("sale__date", "sale_id", "id")
    )

    touched_sale_ids = set()

    for sale_item in sale_items:
        remaining_quantity = sale_item.quantity_kg
        remaining_amount = sale_item.line_total
        total_cost = ZERO_MONEY
        allocated_quantity = ZERO_QTY

        purchase_items = (
            PurchaseItem.objects.filter(
                store_id=sale_item.sale.store_id,
                product_id=sale_item.product_id,
            )
            .select_related("purchase")
            .order_by("purchase__date", "id")
        )

        for purchase_item in purchase_items:
            if remaining_quantity <= ZERO_QTY:
                break

            available_quantity = purchase_item.quantity_kg - allocated_by_purchase[purchase_item.id]
            if available_quantity <= ZERO_QTY:
                continue

            batch_quantity = min(available_quantity, remaining_quantity)
            if batch_quantity == remaining_quantity:
                batch_amount = remaining_amount
            else:
                batch_amount = money(sale_item.line_total * batch_quantity / sale_item.quantity_kg)

            SaleItemBatch.objects.create(
                sale_item_id=sale_item.id,
                purchase_item_id=purchase_item.id,
                quantity=batch_quantity,
                sale_price=sale_item.sale_price_per_kg,
                total_amount=batch_amount,
            )

            allocated_by_purchase[purchase_item.id] += batch_quantity
            allocated_quantity += batch_quantity
            total_cost += batch_quantity * purchase_item.purchase_price_per_kg
            remaining_quantity -= batch_quantity
            remaining_amount -= batch_amount

        if allocated_quantity == sale_item.quantity_kg:
            line_cost_total = money(total_cost)
            cost_price_per_kg = money(total_cost / sale_item.quantity_kg)
            SaleItem.objects.filter(pk=sale_item.pk).update(
                cost_price_per_kg=cost_price_per_kg,
                line_cost_total=line_cost_total,
                profit=money(sale_item.line_total - line_cost_total),
            )
            touched_sale_ids.add(sale_item.sale_id)

    for sale_id in touched_sale_ids:
        totals = SaleItem.objects.filter(sale_id=sale_id)
        total_cost = sum((item.line_cost_total for item in totals), ZERO_MONEY)
        total_amount = sum((item.line_total for item in totals), ZERO_MONEY)
        Sale.objects.filter(pk=sale_id).update(
            total_cost=money(total_cost),
            total_profit=money(total_amount - total_cost),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_saleitembatch"),
    ]

    operations = [
        migrations.RunPython(backfill_sale_item_batches, migrations.RunPython.noop),
    ]
