# Generated by Django 5.2.13 on 2026-04-17 17:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0003_sale_customer_sale_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Изначальная сумма долга')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Остаток долга')),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Оплачен частично'), ('paid', 'Оплачен полностью')], default='unpaid', max_length=20, verbose_name='Статус долга')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='core.customer', verbose_name='Клиент')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='sales.sale', verbose_name='Продажа')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.credit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Оплата по кредиту',
                'verbose_name_plural': 'Оплаты по кредитам',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
