# Generated by Django 5.2.13 on 2026-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('credits', '0001_initial'),
        ('sales', '0003_sale_customer_sale_payment_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['store', 'status'], name='credits_cre_store_i_a147a8_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['customer', 'store'], name='credits_cre_custome_77aae4_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['remaining_amount'], name='credits_cre_remaini_8a9c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['credit', 'date'], name='credits_cre_credit__134f03_idx'),
        ),
    ]
