# Generated by Django 5.2.13 on 2026-05-08 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('credits', '0002_credit_credits_cre_store_i_a147a8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('paid_at', models.DateField(verbose_name='Дата оплаты')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='debt_payments', to='core.customer', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_debt_payments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_debt_payments', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Оплата долга клиента',
                'verbose_name_plural': 'Оплаты долгов клиентов',
                'db_table': 'client_debt_payments',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='client_debt_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='credits.clientdebtpayment', verbose_name='Оплата долга клиента'),
        ),
        migrations.AddIndex(
            model_name='clientdebtpayment',
            index=models.Index(fields=['store', 'client'], name='client_debt_store_i_638859_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdebtpayment',
            index=models.Index(fields=['paid_at'], name='client_debt_paid_at_8231fe_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdebtpayment',
            index=models.Index(fields=['payment_method'], name='client_debt_payment_4f4acc_idx'),
        ),
    ]
