# Generated by Codex on 2026-05-08

from django.db import migrations


def backfill_client_debt_payments(apps, schema_editor):
    ClientDebtPayment = apps.get_model("credits", "ClientDebtPayment")
    CreditPayment = apps.get_model("credits", "CreditPayment")

    for payment in CreditPayment.objects.filter(client_debt_payment__isnull=True).select_related("credit"):
        credit = payment.credit
        client_payment = ClientDebtPayment.objects.create(
            store_id=credit.store_id,
            client_id=credit.customer_id,
            amount=payment.amount,
            payment_method="cash",
            comment=payment.comment,
            paid_at=payment.date,
            employee_id=None,
        )
        ClientDebtPayment.objects.filter(pk=client_payment.pk).update(
            created_at=payment.created_at,
            updated_at=payment.updated_at,
        )
        payment.client_debt_payment_id = client_payment.pk
        payment.save(update_fields=["client_debt_payment"])


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0003_clientdebtpayment_creditpayment_client_debt_payment_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_client_debt_payments,
            migrations.RunPython.noop,
        ),
    ]
