# Generated by Django 5.2.13 on 2026-05-18 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('credits', '0004_backfill_client_debt_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdebtpayment',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='clientdebtpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='clientdebtpayment',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='clientdebtpayment',
            index=models.Index(fields=['status'], name='client_debt_status_34279f_idx'),
        ),
    ]
