# Generated by Django 5.2.13 on 2026-04-16 16:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата закупки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество (кг)')),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена за кг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.product', verbose_name='Товар')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase', verbose_name='Закупка')),
            ],
            options={
                'verbose_name': 'Строка закупки',
                'verbose_name_plural': 'Строки закупки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_transfer_in', 'Поступление в магазин'), ('sale_out', 'Продажа'), ('adjustment_in', 'Корректировка +'), ('adjustment_out', 'Корректировка -')], max_length=30, verbose_name='Тип движения')),
                ('quantity_kg_delta', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Изменение (кг)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Себестоимость за кг')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая себестоимость')),
                ('reference_note', models.CharField(blank=True, max_length=255, verbose_name='Источник / примечание')),
                ('date', models.DateField(verbose_name='Дата движения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движения товара',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество (кг)')),
                ('date', models.DateField(verbose_name='Дата распределения')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.purchaseitem', verbose_name='Строка закупки')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_transfers', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Распределение по магазину',
                'verbose_name_plural': 'Распределения по магазинам',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Остаток (кг)')),
                ('average_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Средняя закупочная цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='core.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Остаток магазина',
                'verbose_name_plural': 'Остатки магазинов',
                'ordering': ['store__name', 'product__name'],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
