# Generated by Django 5.2.13 on 2026-04-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.store', verbose_name='Магазин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'Поступление'), ('sale_out', 'Продажа'), ('adjustment_in', 'Корректировка +'), ('adjustment_out', 'Корректировка -')], max_length=30, verbose_name='Тип движения'),
        ),
        migrations.DeleteModel(
            name='StoreTransfer',
        ),
    ]
