# Generated by Django 5.2.13 on 2026-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0002_purchaseitem_store_alter_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['date', 'supplier'], name='inventory_p_date_62d889_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'store'], name='inventory_p_purchas_138127_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['store', 'product'], name='inventory_p_store_i_466464_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store', 'date'], name='inventory_s_store_i_c0986b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'date'], name='inventory_s_product_51fcd9_idx'),
        ),
    ]
