# Generated by Django 5.2.13 on 2026-04-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='core.store', verbose_name='Магазин')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Оплата поставщику',
                'verbose_name_plural': 'Оплаты поставщикам',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
