# Generated by Django 5.2.13 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_purchaseitem_store_alter_stockmovement_movement_type_and_more"),
        ("payables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpayment",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="inventory.purchase",
                verbose_name="Закупка",
            ),
        ),
    ]
