# Generated by Django 5.2.13 on 2026-04-19

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import DecimalField, ExpressionWrapper, F, Sum, Value
from django.db.models.functions import Coalesce


def backfill_supplier_payment_allocations(apps, schema_editor):
    SupplierPayment = apps.get_model("payables", "SupplierPayment")
    SupplierPaymentAllocation = apps.get_model("payables", "SupplierPaymentAllocation")
    PurchaseItem = apps.get_model("inventory", "PurchaseItem")

    money_field = DecimalField(max_digits=14, decimal_places=2)
    line_total = ExpressionWrapper(
        F("quantity_kg") * F("purchase_price_per_kg"),
        output_field=money_field,
    )

    payment_groups = SupplierPayment.objects.values_list("supplier_id", "store_id").distinct()
    for supplier_id, store_id in payment_groups:
        purchase_rows = list(
            PurchaseItem.objects.filter(
                purchase__supplier_id=supplier_id,
                store_id=store_id,
            )
            .annotate(line_total=line_total)
            .values("purchase_id", "purchase__date")
            .annotate(
                purchase_total=Coalesce(
                    Sum("line_total"),
                    Value(Decimal("0.00"), output_field=money_field),
                )
            )
            .order_by("purchase__date", "purchase_id")
        )

        purchases = [
            {
                "purchase_id": row["purchase_id"],
                "remaining_amount": row["purchase_total"] or Decimal("0.00"),
            }
            for row in purchase_rows
        ]
        purchases_by_id = {row["purchase_id"]: row for row in purchases}

        payments = SupplierPayment.objects.filter(
            supplier_id=supplier_id,
            store_id=store_id,
        ).order_by("date", "id")

        allocations = []
        for payment in payments:
            remaining_payment = payment.amount or Decimal("0.00")
            if remaining_payment <= 0:
                continue

            if payment.purchase_id:
                bound_purchase = purchases_by_id.get(payment.purchase_id)
                if bound_purchase and bound_purchase["remaining_amount"] > 0:
                    applied = min(bound_purchase["remaining_amount"], remaining_payment)
                    if applied > 0:
                        allocations.append(
                            SupplierPaymentAllocation(
                                payment_id=payment.id,
                                purchase_id=payment.purchase_id,
                                store_id=store_id,
                                amount=applied,
                            )
                        )
                        bound_purchase["remaining_amount"] -= applied
                        remaining_payment -= applied

            if remaining_payment > 0:
                for purchase in purchases:
                    if remaining_payment <= 0:
                        break
                    if purchase["remaining_amount"] <= 0:
                        continue

                    applied = min(purchase["remaining_amount"], remaining_payment)
                    if applied <= 0:
                        continue

                    allocations.append(
                        SupplierPaymentAllocation(
                            payment_id=payment.id,
                            purchase_id=purchase["purchase_id"],
                            store_id=store_id,
                            amount=applied,
                        )
                    )
                    purchase["remaining_amount"] -= applied
                    remaining_payment -= applied

        if allocations:
            SupplierPaymentAllocation.objects.bulk_create(allocations)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0002_purchaseitem_store_alter_stockmovement_movement_type_and_more"),
        ("payables", "0002_supplierpayment_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPaymentAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Распределенная сумма")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="payables.supplierpayment", verbose_name="Оплата поставщику")),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_allocations", to="inventory.purchase", verbose_name="Закупка")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="supplier_payment_allocations", to="core.store", verbose_name="Магазин")),
            ],
            options={
                "verbose_name": "Распределение оплаты поставщику",
                "verbose_name_plural": "Распределения оплат поставщикам",
                "ordering": ["payment__date", "payment_id", "purchase_id", "id"],
            },
        ),
        migrations.RunPython(backfill_supplier_payment_allocations, migrations.RunPython.noop),
    ]
