# Generated by Django 5.2.13 on 2026-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_purchase_inventory_p_date_62d889_idx_and_more'),
        ('payables', '0003_supplierpaymentallocation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'store', 'date'], name='payables_su_supplie_b28461_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['purchase', 'store'], name='payables_su_purchas_171840_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['payment', 'purchase'], name='payables_su_payment_d3e83c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['store', 'purchase'], name='payables_su_store_i_1d8d21_idx'),
        ),
    ]
