# Generated by Django 5.2.13 on 2026-05-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0004_supplierpayment_payables_su_supplie_b28461_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
