# Generated by Django 5.2.13 on 2026-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0004_purchase_deleted_at'),
        ('payables', '0005_supplierpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['status'], name='payables_su_status_75b5ea_idx'),
        ),
    ]
