# Generated by Django 5.2.13 on 2026-05-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payables', '0006_supplierpayment_cancel_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOverpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма переплаты')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток переплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overpayment', to='payables.supplierpayment', verbose_name='Исходная оплата')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_overpayments', to='core.store', verbose_name='Магазин')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overpayments', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Переплата поставщику',
                'verbose_name_plural': 'Переплаты поставщикам',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['supplier', 'store', 'created_at'], name='payables_su_supplie_388304_idx')],
            },
        ),
    ]
