# Generated by Django 5.2.13 on 2026-04-20 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма аванса')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_advances', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_advances', to='core.seller', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_advances', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Подотчетный аванс',
                'verbose_name_plural': 'Подотчетные авансы',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма расхода')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.employeeadvance', verbose_name='Аванс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.seller', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_expenses', to='core.store', verbose_name='Магазин')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Расход сотрудника',
                'verbose_name_plural': 'Расходы сотрудников',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
