# Generated by Django 5.2.13 on 2026-04-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата выплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма зарплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_payments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='core.seller', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплаты',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма расхода')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_expenses', to='expenses.expensecategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_expenses', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Расход магазина',
                'verbose_name_plural': 'Расходы магазина',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
