# Generated by Django 5.2.13 on 2026-04-20 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('expenses', '0002_salarypayment_storeexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeadvance',
            index=models.Index(fields=['store', 'date', 'seller'], name='expenses_em_store_i_922f07_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeadvance',
            index=models.Index(fields=['seller', 'date'], name='expenses_em_seller__faba85_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['store', 'date', 'seller'], name='expenses_ex_store_i_dad670_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='expenses_ex_categor_9e3535_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['advance'], name='expenses_ex_advance_0725ba_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['store', 'date', 'seller'], name='expenses_sa_store_i_b7fc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='storeexpense',
            index=models.Index(fields=['store', 'date', 'category'], name='expenses_st_store_i_6ade8a_idx'),
        ),
    ]
