# Generated by Django 5.2.13 on 2026-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_employeeadvance_expenses_em_store_i_922f07_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeexpense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удален'),
        ),
    ]
